void BriAllocateRpcBuffer() {}
void BriCleanup() {}
void BriCreateBrokeredEvent() {}
void BriCreateBrokeredEventEx() {}
void BriDeleteBrokeredEvent() {}
void BriFreeRpcBuffer() {}
void BriGetBrokerAvailabilityChangeStamp() {}
void BriIsBrokerRegistered() {}
void BriRegisterToBrokerAvailability() {}
void BriResolveBrokerIdByEventId() {}
void BriUnregisterFromBrokerAvailability() {}
void EACreateAggregateEvent() {}
void EADeleteAggregateEvent() {}
void EAEnumerateAggregateEvents() {}
void EAQueryAggregateEventData() {}
void EaCreateAggregatedEvent() {}
void EaCreateAggregation() {}
void EaDecodeBrokeredEvent() {}
void EaDeleteAggregatedEvent() {}
void EaDeleteAggregatedEventParameters() {}
void EaDeleteAggregation() {}
void EaDisableAggregatedEvent() {}
void EaEnableAggregatedEvent() {}
void EaEncodeBrokeredEvent() {}
void EaFreeAggregatedEventParameters() {}
void EaFreeBuffer() {}
void EaGetAggregation() {}
void EaQueryAggregateEventConditionState() {}
void EaQueryAggregatedEvent() {}
void EaQueryAggregatedEventParameters() {}
void EaSignalAggregatedEvent() {}
void EaStoreAggregatedEventParameters() {}
